apiVersion: v1
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      uid: prometheus
      url: http://kube-prometheus-stack-prometheus.monitoring:9090/
      access: proxy
      isDefault: true
      jsonData:
        timeInterval: 30s
    - access: proxy
      basicAuth: false
      jsonData:
        derivedFields:
        - datasourceUid: Tempo
          matcherRegex: ((\d+|[a-z]+)(\d+|[a-z]+)(\d+|[a-z]+)(\d+|[a-z]+)(\d+|[a-z]+)(\d+|[a-z]+)(\d+|[a-z]+)(\d+|[a-z]+)(\d+|[a-z]+)(\d+|[a-z]+)(\d+|[a-z]+))
          name: TraceID
          url: "$${__value.raw}"
        maxLines: 2000
        tlsSkipVerify: true
      name: Loki
      type: loki
      url: http://loki-gateway.loki.svc
    - access: proxy
      jsonData:
        httpMethod: GET
        lokiSearch:
          datasourceUid: Loki
        nodeGraph:
          enabled: true
        search:
          hide: false
        tlsSkipVerify: true
        tracesToLogs:
          datasourceUid: Loki
          filterBySpanID: true
          filterByTraceID: true
          mapTagNamesEnabled: true
          mappedTags:
          - key: service.name
            value: service
          spanEndTimeShift: 1h
          spanStartTimeShift: 1h
          tags:
          - job
          - instance
          - pod
          - namespace
      name: Tempo
      type: tempo
      url: http://tempo-tempo-distributed-query-frontend.tempo.svc:3100
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: kube-prometheus-stack
    meta.helm.sh/release-namespace: monitoring
  labels:
    app: kube-prometheus-stack-grafana
    app.kubernetes.io/instance: kube-prometheus-stack
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 39.4.0
    chart: kube-prometheus-stack-39.4.0
    grafana_datasource: "1"
    heritage: Helm
    release: kube-prometheus-stack
  name: kube-prometheus-stack-grafana-datasource
  namespace: monitoring
